### ISSUE TITLE
Nimbus CL < > Lodestar VC incompatibility

### ISSUE THREAD

**Issue by barnabasbusa** [ChainSafe/lodestar#6636]
### Describe the bug

We are in the process to test cross beacon <> validator client compatibility, and found a bug when testing nimbus CL with lodestar VC. 

Lodestar reports:
```sh
Apr-05 13:41:53.163[]                error: Error proposing block slot=6, validator=0x889f…366b - JSON expected key slot is undefined - Failed to produce block
Error: JSON expected key slot is undefined - Failed to produce block
    at ContainerType.fromJson (/usr/app/node_modules/@chainsafe/ssz/src/type/container.ts:347:15)
    at Object.fromJson (file:///usr/app/packages/api/src/utils/types.ts:156:44)
    at Object.fromJson (file:///usr/app/packages/api/src/utils/types.ts:198:15)
    at Object.fromJson (file:///usr/app/packages/api/src/beacon/routes/validator.ts:778:91)
    at Object.request [as produceBlockV3] (file:///usr/app/packages/api/src/utils/client/client.ts:91:50)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BlockProposingService.produceBlockWrapper (file:///usr/app/packages/validator/src/services/block.ts:205:17)
    at BlockProposingService.createAndPublishBlock (file:///usr/app/packages/validator/src/services/block.ts:144:29)
    at async Promise.all (index 0)
```

Nimbus reports:
```sh
nothing out of the ordinary
```

Snooper between cl <> vc reports:
```sh
nothing out of the ordinary
```

### Operating system

Linux

### Nimbus version or commit hash

`statusim/nimbus-eth2:multiarch-latest - sha256:8e79e02b37351bdcf0a4b07c9cb5a8dd23afdf83144a0d948644b72884cdd10d`

### Expected behavior

I would expect all client combinations would work. 

### Steps to reproduce

config.yaml: 
```yaml
participants:
  - cl_type: nimbus
    vc_type: lodestar
    vc_image: chainsafe/lodestar:next
additional_services:
  - dora
snooper_enabled: true
global_log_level: debug
```
`kurtosis run github.com/kurtosis-tech/ethereum-package --args-file config.yaml`

### Additional context

[Current BN <> VC Compatibility list tracker](https://github.com/kurtosis-tech/ethereum-package?tab=readme-ov-file#beacon-node--validator-client-compatibility)

![Screenshot 2024-04-05 at 14 08 53](https://github.com/ChainSafe/lodestar/assets/21987084/4ba19a53-36d3-4d39-b563-3dc1f90b2fef)

### Operating system

Linux

### Lodestar version or commit hash

Version: v1.17.0/898cd90

cc: @pk910

**Comment by nflaig** [comment]
Thanks for all the detailed issues, this is great! This specific issue should be fixed by https://github.com/ChainSafe/lodestar/pull/6576 already (not yet released).

I am not exactly sure which commit hash you are running, it looks like docker hub does not provide a way to query the digest of an older version of a tag. I am also not able to pull it via digest anymore.

The commit hash can be printed out by running
```sh
docker run --rm <lodestar_image> --help
```

**Comment by barnabasbusa** [comment]
```
docker run --rm -it chainsafe/lodestar:next --help
🌟 Lodestar: TypeScript Implementation of the Ethereum Consensus Beacon Chain.

 * Version: v1.17.0/898cd90
  * by ChainSafe Systems, 2018-2024
  ```

**Comment by nflaig** [comment]
> ```
> docker run --rm -it chainsafe/lodestar:next --help
> 🌟 Lodestar: TypeScript Implementation of the Ethereum Consensus Beacon Chain.
> 
>  * Version: v1.17.0/898cd90
>   * by ChainSafe Systems, 2018-2024
> ```

The digest of this image is `sha256:8d1ead7f7e0fbabb0431f4fb751c76128be0542701e89ab7b0b3719f82ac101f` (see [docker hub](https://hub.docker.com/layers/chainsafe/lodestar/next/images/sha256-f8c545674bf41127b310275e641c7dd1da69dbea76c7eb1f7991f34d50afe31a?context=explore)) which is different from what was referenced in the issue.

**Comment by barnabasbusa** [comment]
I must have had an older image locally stored for next. My bad! Nevertheless the issue persists, its just another error. 

```sh
Apr-05 13:41:53.163[]                error: Error proposing block slot=6, validator=0x889f…366b - JSON expected key slot is undefined - Failed to produce block
Error: JSON expected key slot is undefined - Failed to produce block
    at ContainerType.fromJson (/usr/app/node_modules/@chainsafe/ssz/src/type/container.ts:347:15)
    at Object.fromJson (file:///usr/app/packages/api/src/utils/types.ts:156:44)
    at Object.fromJson (file:///usr/app/packages/api/src/utils/types.ts:198:15)
    at Object.fromJson (file:///usr/app/packages/api/src/beacon/routes/validator.ts:778:91)
    at Object.request [as produceBlockV3] (file:///usr/app/packages/api/src/utils/client/client.ts:91:50)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BlockProposingService.produceBlockWrapper (file:///usr/app/packages/validator/src/services/block.ts:205:17)
    at BlockProposingService.createAndPublishBlock (file:///usr/app/packages/validator/src/services/block.ts:144:29)
    at async Promise.all (index 0)
```

**Comment by nflaig** [comment]
> I must have had an older image locally stored for next

Based on the Nimbus log from https://github.com/ChainSafe/lodestar/issues/6634
```
agent_version=Lodestar/v1.17.0/def26ac node=http://172.16.0.28:8562[Lodestar/v1.17.0/def26ac] node_index=0 node_roles=AGBSDT
```
The commit the referenced image is build from is https://github.com/ChainSafe/lodestar/commit/def26ac2c463e8206f359167e1638eadde72be5c which did not include the `skip_randao_verification` fix yet, so this seems to be resolved at least.

> its just another error.

That's a strange one, needs further investigation

**Comment by nflaig** [comment]
> I must have had an older image locally stored for next. My bad! Nevertheless the issue persists, its just another error.
> 
> ```shell
> Apr-05 13:41:53.163[]                error: Error proposing block slot=6, validator=0x889f…366b - JSON expected key slot is undefined - Failed to produce block
> Error: JSON expected key slot is undefined - Failed to produce block
>     at ContainerType.fromJson (/usr/app/node_modules/@chainsafe/ssz/src/type/container.ts:347:15)
>     at Object.fromJson (file:///usr/app/packages/api/src/utils/types.ts:156:44)
>     at Object.fromJson (file:///usr/app/packages/api/src/utils/types.ts:198:15)
>     at Object.fromJson (file:///usr/app/packages/api/src/beacon/routes/validator.ts:778:91)
>     at Object.request [as produceBlockV3] (file:///usr/app/packages/api/src/utils/client/client.ts:91:50)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at BlockProposingService.produceBlockWrapper (file:///usr/app/packages/validator/src/services/block.ts:205:17)
>     at BlockProposingService.createAndPublishBlock (file:///usr/app/packages/validator/src/services/block.ts:144:29)
>     at async Promise.all (index 0)
> ```

This error seems to happen during deserialization of the response
https://github.com/ChainSafe/lodestar/blob/898cd903bf9d65836ac06e43740efcc5404fe615/packages/api/src/beacon/routes/validator.ts#L778

It's a bit strange that we try to parse it as a `BlindedBeaconBlock`. I am assuming the blocks are full blocks and we actually receive `BlockContents` (post deneb).

A possible reason for this could be that Nimbus is sending `execution_payload_blinded` as a [string value](https://github.com/status-im/nimbus-eth2/blob/dc19b082a9850bf9333e2371ea22230b61c2d501/beacon_chain/spec/eth2_apis/eth2_rest_serialization.nim#L3365) instead of [boolean as per spec](https://github.com/ethereum/beacon-APIs/blob/fc89ec5c5f0904a0057fc543f0eb4ddaa480f04e/apis/validator/block.v3.yaml#L102-L104).

**Comment by nflaig** [comment]
Fixed by https://github.com/status-im/nimbus-eth2/pull/6204
